Repository ramboxapp/community-edition, pull requests merged in 2019-04, with the labels that each got.

#2160 Allow mainWindow to be undefined
  electron/main.js
Labels: bug

#2144 feat: #2101 Add option to hide tabbar labels
  app/ux/WebView.js
  app/view/preferences/Preferences.js
  electron/main.js
  resources/languages/af.js
  resources/languages/bg.js
  resources/languages/bn.js
  resources/languages/bs2.js
  resources/languages/ca.js
  resources/languages/ceb.js
  resources/languages/cs.js
  resources/languages/da.js
  resources/languages/de-CH.js
  resources/languages/de.js
  resources/languages/en.js
  resources/languages/fi.js
  resources/languages/fil.js
  resources/languages/fr.js
  resources/languages/he.js
  resources/languages/hi.js
  resources/languages/hr.js
  resources/languages/hu.js
  resources/languages/it.js
  resources/languages/ja.js
  resources/languages/nl.js
  resources/languages/no.js
  resources/languages/pl.js
  resources/languages/pt-BR.js
  resources/languages/pt-PT.js
  resources/languages/ro.js
  resources/languages/sk.js
  resources/languages/sr.js
  resources/languages/sv-SE.js
  resources/languages/uk.js
  resources/languages/vi.js
  resources/languages/zh-CN.js
  resources/languages/zh-TW.js
Labels: enhancement

#2055 Fixed external link opening for discord service
  app/store/ServicesList.js
Labels: service-bug

#2050 Added Google Calendar
  app/store/ServicesList.js
  resources/icons/googlecalendar.png
Labels: new service

#2034 Edited gmail notification check
  app/store/ServicesList.js
Labels: service-bug

#2206 Fix issue with electron before-input-event
  app/ux/WebView.js
  package-lock.json
  package.json
  resources/js/rambox-service-api.js
Labels: bug

#2205 Fix invalid version whatsapp
  app/store/ServicesList.js
  app/ux/WebView.js
Labels: bug

#2223 Added search in page feature
  app/Application.js
  package-lock.json
  package.json
  resources/js/rambox-service-api.js
Labels: enhancement

#2219 Allow to send accept language header to websites, according to settings & edited getUserAgent regexp
  app/ux/WebView.js
  electron/main.js
Labels: enhancement

#2231 Fix copy past not working master password
  masterpassword.html
Labels: bug

#2230 Fix input bypass
  app/view/main/MainController.js
Labels: bug

#2229 Set inputType as password
  app/view/preferences/Preferences.js
Labels: enhancement

#2227 Fixed snap build config : added camera plug
  package.json
Labels: enhancement

#2232 Allow to disable no connection message
  electron/main.js
  index.html
  package-lock.json
  package.json
Labels: enhancement
